### ISSUE TITLE
Does not work with case statements

### ISSUE THREAD

**Issue by padde** [stevenharman/dumb_delegator#11]
While dumb delegator allows us to forward `is_a?` and `class` to the delegate, it does not work with `case` statements, which internally uses the `===` operator:

``` ruby
MyAwesomeClass  = Class.new

o = MyAwesomeClass.new
d = DumbDelegator.new(o)

case d
when MyAwesomeClass then 'awesome'
when DumbDelegator then 'not so awesome'
else 'not awesome at all'
end
#=> 'not so awesome'
```

The original comparison is done in C so the changed `kind_of?` method is not in effect:

```
From: object.c (C Method):
Owner: Module
Visibility: public
Number of lines: 5

static VALUE
rb_mod_eqq(VALUE mod, VALUE arg)
{
    return rb_obj_is_kind_of(arg, mod);
}
```

I suppose a solution would require to monkey patch `Module#===`. For example

``` ruby
class Module
  def ===(other)
    other.kind_of?(self)
  end
end
```

If you like I can make a PR for this but I wanted to hear your opinion first.

Thanks!

**Comment by stevenharman** [comment]
Hello @padde, and thanks for looking into this. I have a sense that we discussed this at one point in the past, but can find no record of such a discussion. I don't like the idea of money-patching `Module` as that's pretty invasive. Are there other options?

**Comment by padde** [comment]
Not that I am aware of, unfortunately. I don't like the monkey patch either, a solution without would definitely be great but I don't think it's possible due to the way how `===` is implemented.
